services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=supershoppingservice
      - POSTGRES_USER=sssadmin
      - POSTGRES_PASSWORD=ssspassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sss-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5431:5431"
    depends_on:
      - postgres
    environment:
      - DB_HOST=db
      - DB_USER=sssadmin
      - DB_PASSWORD=ssspassword
      - DB_NAME=supershoppingservice
    networks:
      - sss-network

  # Comment out client for local build (npm run dev)
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - sss-network

volumes:
  postgres_data:

networks:
  sss-network: