services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=tracrio
      - DB_PASSWORD=tracrioPassword
      - DB_NAME=Tracr-io
    command: npm start

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: Tracr-io
      POSTGRES_USER: tracrio
      POSTGRES_PASSWORD: tracrioPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
