services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=tracrio
      - POSTGRES_USER=tracradmin
      - POSTGRES_PASSWORD=tracrpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tracrio-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5431:5431"
    depends_on:
      - postgres
    environment:
      - DB_HOST=db
      - DB_USER=tracradmin
      - DB_PASSWORD=tracrpassword
      - DB_NAME=tracrio
    networks:
      - tracrio-network

volumes:
  postgres_data:

networks:
  tracrio-network: